version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - cd /home/ec2-user/server
      - npm install

artifacts:
  files: '**/*'
  base-directory: /home/ec2-user/server/build
  discard-paths: yes

cache:
  paths:
    - '/home/ec2-user/server/node_modules/**/*'
